# My Projects

projects:
  - title: "Zug fahren"
    url: "https://zug-fahren-tmp.vercal.app"
    description: "a little picture gallery website with some aesthetics"
    lastUpdated: "2026-03-27"

  # - title: "Watch free!"
  #   url: "https://watchnexoknights.vercel.app/"
  #   descriptionription: "a website which provides free legal links and information to watch series!"
  #   lastUpdated: "2025-03-27"

  # - title: "Open CMD on Hotkey"
  #   url: "https://github.com/ShadowDara/open-cmd-on-Hotkey"
  #   descriptionription: "Open a command prompt in the current directory using a hotkey on Windows!"
  #   lastUpdated: "2025-03-27"

  - title: "Ninjago Akinator"
    url: "/r/a"
    dateCreated: "2026-05-05"
    lastUpdated: null
    description: "er errät jeden Ninjago Character an den du denkst!"
    cat: "tool"
    color: "#fffb1b"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"
    showcase: true

  - title: "My Webpage"
    dateCreated: "2025-02-27"
    lastUpdated: null
    description: "a long Page"
    cat: "tool"
    color: "#fffb1b"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Awesome Minecraft Tools"
    dateCreated: "2025-07-31"
    lastUpdated: "2026-04-18"
    description: "a Collection for Minecraft Related Stuff"
    cat: "tool"
    color: "#fffb1b"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"


  # MC Content
  - title: "betterbackups"
    dateCreated: "2025-09-02"
    lastUpdated: null
    description: "a Mod to view your Minecraft backups"
    cat: "tool"
    color: "#ff0000"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "World Viewer"
    dateCreated: "2026-04-17"
    lastUpdated: null
    description: "a Mod to view your Minecraft Worlds and their Data"
    cat: "tool"
    color: "#ff0000"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Simple Timer"
    dateCreated: "2024-03-13"
    lastUpdated: "2025-08-17"
    description: "a Timer Datapack for Minecraft"
    cat: "tool"
    color: "#ff0000"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"


  # Tools
  - title: "Search Engine"
    dateCreated: "2024-10-22"
    lastUpdated: "2024-10-29"
    description: "File Directory Search Engine in Python — my first time coding outside of school."
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "KeyValueParser"
    dateCreated: "2026-02-11"
    lastUpdated: "2026-03-24"
    description: "a simple KeyValueParser Libary written in C++"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Copper Tools (MC)"
    dateCreated: "2025-08-01"
    lastUpdated: "2025-09-08"
    description: "a minecraft fabric mod for 1.20.1 which ads copper tools and armor"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "SX"
    dateCreated: "2026-02-19"
    lastUpdated: "2026-03-24"
    description: "a simple shortcuter programm for long commands in C++"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"
    showcase: true

  - title: "NotenPunkteUmrechner"
    dateCreated: "2025-11-05"
    lastUpdated: "2026-02-21"
    description: "Convertiert Notenpunkte zu Noten und in die andere Richtung."
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "bt"
    dateCreated: "2026-04-09"
    lastUpdated: null
    description: "a simple cli tool which should help with building"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Linksaver"
    dateCreated: "2026-01-31"
    lastUpdated: "2026-04-25"
    description: "a cli tools to save links for example which u used in your game project"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Automatic MD Index"
    dateCreated: "2025-05-10"
    lastUpdated: "2026-04-18"
    description: "an npm module to create an index for Markdown files"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "graphicscardinstaller"
    dateCreated: "2025-05-12"
    lastUpdated: "2025-08-19"
    description: "Just Install a new Graphic Card! - DISCLAIMER! Just a troll, no Virus!"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Video Converter"
    dateCreated: "2025-09-13"
    lastUpdated: "2025-11-22"
    description: "a video converter in Kotlin which uses ffmpeg to convert videos to preset formats"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"
    showcase: true

  - title: "filebox"
    dateCreated: "2025-09-02"
    lastUpdated: "2025-10-22"
    description: "a server where users can upload files with a sharelink which exist for choosen period of time"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Pix"
    dateCreated: "2026-01-09"
    lastUpdated: "2026-03-13"
    description: "an Image Viewer for Pixel Art Pictures!"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Repo Database Creator"
    dateCreated: "2025-04-10"
    lastUpdated: "2025-05-10"
    description: "View GitHub repositories for a user and sort them"
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "3ma-to-obj"
    dateCreated: "2025-03-16"
    lastUpdated: "2025-04-09"
    description: "Python script to convert 3ma files to .obj format."
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Date Calculator"
    url: "https://shadowdara.github.io/date-calculator"
    dateCreated: "2025-04-11"
    lastUpdated: "2025-04-22"
    description: "An easy calculator for important days and time intervals."
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "Fling lang"
    dateCreated: "2025-10-24"
    lastUpdated: "2026-03-28"
    description: "First attempt at building a programming language in C++."
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  - title: "finder"
    dateCreated: "2025-11-17"
    lastUpdated: null
    url: "https://github.com/shadowdara/finder"
    showcase: true
    description: "A CLI tool to find your files and projects."
    cat: "tool"
    color: "#7F77DD"
    textColor: "#3C3489"
    bgLight: "#EEEDFE"

  # Frameworks
  - title: "samengine"
    dateCreated: "2026-04-04"
    lastUpdated: null
    showcase: true
    url: "https://samengine.vercal.app"
    description: "a small and fast Browser Game Library written in Typescript"
    cat: "framework"
    color: "#378ADD"
    textColor: "#0C447C"
    bgLight: "#E6F1FB"

  # Games
  - title: "Visual Novel"
    dateCreated: "2025-03-19"
    lastUpdated: "2025-05-23"
    description: "A simple Visual Novel made for the nanoremo game jam."
    cat: "game"
    color: "#1D9E75"
    textColor: "#085041"
    bgLight: "#E1F5EE"

  - title: "Shadow-Paths"
    dateCreated: "2024-10-31"
    lastUpdated: "2024-11-10"
    description: "A little Python text adventure game."
    cat: "game"
    color: "#1D9E75"
    textColor: "#085041"
    bgLight: "#E1F5EE"

  - title: "justLook"
    dateCreated: "2026-01-19"
    lastUpdated: "2026-02-28"
    url: "https://shadowdara.itch.io/just-Look"
    description: "a mysterious Game where you have escape from a creepy House."
    showcase: true
    cat: "game"
    color: "#1D9E75"
    textColor: "#085041"
    bgLight: "#E1F5EE"

  - title: "Piggy Game"
    dateCreated: "2026-01-31"
    lastUpdated: "2026-02-10"
    description: "a Game where you play as Pig which need to escape the Farmer"
    cat: "game"
    color: "#1D9E75"
    textColor: "#085041"
    bgLight: "#E1F5EE"
